name: Run Python Code

on:
  schedule:
    - cron: "*/5 * * * *" # 5분마다 실행
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --only-binary=pandas -r requirements.txt

      - name: Download existing artifact
        uses: actions/download-artifact@v3
        with:
          name: danawa_lowest_prices
          path: .
          continue-on-error: true

      - name: Run Python script
        run: python danawa_lowest_crawler.py

      - name: Upload updated artifact
        uses: actions/upload-artifact@v3
        with:
          name: danawa_lowest_prices
          path: danawa_lowest_prices_*.xlsx
